version: '2'

services:

  blazegraph:
    image: gridappsd/blazegraph:develop
    # image: gridappsd/blazegraph:seto4
    container_name: blazegraph
    ports:
      - 8889:8080

  neo4j-apoc:
    image: neo4j:5.22-community
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_PLUGINS= ["apoc", "n10s"]
      - NEO4J_AUTH=none
      - NEO4J_dbms_memory_transaction_total_max=10g
      - NEO4J_server_memory_heap_max__size=10g
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    volumes:
      - ./docker/neo4j/data:/data
      - ./docker/neo4j/plugins:/plugins


  graphdb:
    image: ontotext/graphdb:10.7.3
    ports:
      - 7200:7200
    volumes:
      - ./docker/graphdb:/opt/graphdb/home

  mysql:
    image: mysql:8.1.0
    container_name: mysql_json
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PORT: 3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
