from cimgraph.queries.sparql.get_all_edges import get_all_edges_sparql
from cimgraph.queries.sparql.get_all_nodes import get_all_nodes_sparql
from cimgraph.queries.sparql.upload_triples import upload_triples_sparql
