from __future__ import annotations
import logging
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional
from cimgraph.data_profile.identity import Identity, stereotype
from cimgraph.data_profile.units import CIMUnit, UnitSymbol, UnitMultiplier
_log = logging.getLogger(__name__)
'''
Annotated CIMantic Graphs data profile for GeographicalLocation
Generated by CIMTool http://cimtool.org
'''

class CIMStereotype(Enum):
    Attribute = "Attribute"
    ByReference = "ByReference"
    Compound = "Compound"
    Concrete = "Concrete"
    Primitive = "Primitive"

BASE_URI = 'http://ucaiug.org/ns/CGMES/GeographicalLocation-EU/3.0#'
ONTOLOGY_URI = 'http://iec.ch/TC57/CIM100#'

@dataclass(repr=False)
class IdentifiedObject(Identity):
    '''
    This is a root class to provide common identification for all classes needing
    identification and naming attributes.
    '''

    mRID: Optional[str] = field(
        default=None,
        metadata={
        'type': 'Attribute',
        'stereotypes': ['Attribute'],
        'minOccurs': '1',
        'maxOccurs': '1',
        'namespace': 'http://iec.ch/TC57/CIM100#',
        'serialize': True,
        })
    '''
    Master resource identifier issued by a model authority. The mRID is
    unique within an exchange context. Global uniqueness is easily achieved
    by using a UUID, as specified in RFC 4122, for the mRID. The use of
    UUID is strongly recommended.
    For CIMXML data files in RDF syntax conforming to IEC 61970-552, the
    mRID is mapped to rdf:ID or rdf:about attributes that identify CIM
    object elements.
    '''
    
    name: Optional[str] = field(
        default=None,
        metadata={
        'type': 'Attribute',
        'stereotypes': ['Attribute'],
        'minOccurs': '0',
        'maxOccurs': '1',
        'namespace': 'http://iec.ch/TC57/CIM100#',
        'serialize': True,
        })
    '''
    The name is any free human readable and possibly non unique text naming
    the object.
    '''
    
    @property
    def __namespace__(self):
        return 'http://iec.ch/TC57/CIM100#'
    @property
    def __package__(self):
        return 'Core'
    @property
    def __minOccurs__(self):
        return '0'
    @property
    def __maxOccurs__(self):
        return 'unbounded'
    
@stereotype(CIMStereotype.Concrete)
@dataclass(repr=False)
class CoordinateSystem(IdentifiedObject):
    '''
    Coordinate reference system.
    '''

    crsUrn: Optional[str] = field(
        default=None,
        metadata={
        'type': 'Attribute',
        'stereotypes': ['Attribute'],
        'minOccurs': '1',
        'maxOccurs': '1',
        'namespace': 'http://iec.ch/TC57/CIM100#',
        'serialize': True,
        })
    '''
    A Uniform Resource Name (URN) for the coordinate reference system (crs)
    used to define 'Location.PositionPoints'.
    An example would be the European Petroleum Survey Group (EPSG) code
    for a coordinate reference system, defined in URN under the Open Geospatial
    Consortium (OGC) namespace as: urn:ogc:def:crs:EPSG::XXXX, where XXXX
    is an EPSG code (a full list of codes can be found at the EPSG Registry
    web site http://www.epsg-registry.org/). To define the coordinate system
    as being WGS84 (latitude, longitude) using an EPSG OGC, this attribute
    would be urn:ogc:def:crs:EPSG::4236.
    A profile should limit this code to a set of allowed URNs agreed to
    by all sending and receiving parties.
    '''
    
    Locations: list[Location] = field(
        default_factory=list,
        metadata={
        'type': 'Association',
        'stereotypes': [],
        'minOccurs': '0',
        'maxOccurs': 'unbounded',
        'inverse': 'Location.CoordinateSystem',
        'namespace': 'http://iec.ch/TC57/CIM100#',
        'serialize': False,
        })
    '''
    All locations described with position points in this coordinate system.
    '''
    
    @property
    def __namespace__(self):
        return 'http://iec.ch/TC57/CIM100#'
    @property
    def __package__(self):
        return 'Common'
    @property
    def __minOccurs__(self):
        return '0'
    @property
    def __maxOccurs__(self):
        return 'unbounded'
    
@stereotype(CIMStereotype.Concrete)
@dataclass(repr=False)
class Location(IdentifiedObject):
    '''
    The place, scene, or point of something where someone or something has
    been, is, and/or will be at a given moment in time. It can be defined with
    one or more position points (coordinates) in a given coordinate system.
    '''

    CoordinateSystem: Optional[CoordinateSystem] = field(
        default=None,
        metadata={
        'type': 'Association',
        'stereotypes': ['ByReference'],
        'minOccurs': '1',
        'maxOccurs': '1',
        'inverse': 'CoordinateSystem.Locations',
        'namespace': 'http://iec.ch/TC57/CIM100#',
        'serialize': True,
        })
    '''
    Coordinate system used to describe position points of this location.
    '''
    
    PowerSystemResources: Optional[PowerSystemResource] = field(
        default=None,
        metadata={
        'type': 'Association',
        'stereotypes': ['ByReference'],
        'minOccurs': '1',
        'maxOccurs': '1',
        'inverse': 'PowerSystemResource.Location',
        'namespace': 'http://iec.ch/TC57/CIM100#',
        'serialize': True,
        })
    '''
    All power system resources at this location.
    '''
    
    PositionPoints: list[PositionPoint] = field(
        default_factory=list,
        metadata={
        'type': 'Association',
        'stereotypes': [],
        'minOccurs': '0',
        'maxOccurs': 'unbounded',
        'inverse': 'PositionPoint.Location',
        'namespace': 'http://iec.ch/TC57/CIM100#',
        'serialize': False,
        })
    '''
    Sequence of position points describing this location, expressed in
    coordinate system 'Location.CoordinateSystem'.
    '''
    
    @property
    def __namespace__(self):
        return 'http://iec.ch/TC57/CIM100#'
    @property
    def __package__(self):
        return 'Common'
    @property
    def __minOccurs__(self):
        return '0'
    @property
    def __maxOccurs__(self):
        return 'unbounded'
    
@dataclass(repr=False)
class WorkLocation(Location):
    '''
    Information about a particular location for various forms of work.
    '''

    @property
    def __namespace__(self):
        return 'http://iec.ch/TC57/CIM100#'
    @property
    def __package__(self):
        return 'Work'
    @property
    def __minOccurs__(self):
        return '0'
    @property
    def __maxOccurs__(self):
        return 'unbounded'
    
@stereotype(CIMStereotype.Concrete)
@dataclass(repr=False)
class ServiceLocation(WorkLocation):
    '''
    A real estate location, commonly referred to as premises.
    '''

    @property
    def __namespace__(self):
        return 'http://iec.ch/TC57/CIM100#'
    @property
    def __package__(self):
        return 'Customers'
    @property
    def __minOccurs__(self):
        return '0'
    @property
    def __maxOccurs__(self):
        return 'unbounded'
    
@dataclass(repr=False)
class PowerSystemResource(IdentifiedObject):
    '''
    A power system resource (PSR) can be an item of equipment such as a switch,
    an equipment container containing many individual items of equipment such
    as a substation, or an organisational entity such as sub-control area.
    Power system resources can have measurements associated.
    '''

    Location: Optional[Location] = field(
        default=None,
        metadata={
        'type': 'Association',
        'stereotypes': [],
        'minOccurs': '0',
        'maxOccurs': '1',
        'inverse': 'Location.PowerSystemResources',
        'namespace': 'http://iec.ch/TC57/CIM100#',
        'serialize': False,
        })
    '''
    Location of this power system resource.
    '''
    
    @property
    def __namespace__(self):
        return 'http://iec.ch/TC57/CIM100#'
    @property
    def __package__(self):
        return 'Core'
    @property
    def __minOccurs__(self):
        return '0'
    @property
    def __maxOccurs__(self):
        return 'unbounded'
    
@stereotype(CIMStereotype.Concrete)
@dataclass(repr=False)
class PositionPoint(Identity):
    '''
    Set of spatial coordinates that determine a point, defined in the coordinate
    system specified in 'Location.CoordinateSystem'. Use a single position
    point instance to describe a point-oriented location. Use a sequence of
    position points to describe a line-oriented object (physical location of
    non-point oriented objects like cables or lines), or area of an object
    (like a substation or a geographical zone - in this case, have first and
    last position point with the same values).
    '''

    sequenceNumber: Optional[int] = field(
        default=None,
        metadata={
        'type': 'Attribute',
        'stereotypes': ['Attribute'],
        'minOccurs': '0',
        'maxOccurs': '1',
        'namespace': 'http://iec.ch/TC57/CIM100#',
        'serialize': True,
        })
    '''
    Zero-relative sequence number of this point within a series of points.
    '''
    
    xPosition: Optional[str] = field(
        default=None,
        metadata={
        'type': 'Attribute',
        'stereotypes': ['Attribute'],
        'minOccurs': '1',
        'maxOccurs': '1',
        'namespace': 'http://iec.ch/TC57/CIM100#',
        'serialize': True,
        })
    '''
    X axis position.
    '''
    
    yPosition: Optional[str] = field(
        default=None,
        metadata={
        'type': 'Attribute',
        'stereotypes': ['Attribute'],
        'minOccurs': '1',
        'maxOccurs': '1',
        'namespace': 'http://iec.ch/TC57/CIM100#',
        'serialize': True,
        })
    '''
    Y axis position.
    '''
    
    zPosition: Optional[str] = field(
        default=None,
        metadata={
        'type': 'Attribute',
        'stereotypes': ['Attribute'],
        'minOccurs': '0',
        'maxOccurs': '1',
        'namespace': 'http://iec.ch/TC57/CIM100#',
        'serialize': True,
        })
    '''
    (if applicable) Z axis position.
    '''
    
    Location: Optional[Location] = field(
        default=None,
        metadata={
        'type': 'Association',
        'stereotypes': ['ByReference'],
        'minOccurs': '1',
        'maxOccurs': '1',
        'inverse': 'Location.PositionPoints',
        'namespace': 'http://iec.ch/TC57/CIM100#',
        'serialize': True,
        })
    '''
    Location described by this position point.
    '''
    
    @property
    def __namespace__(self):
        return 'http://iec.ch/TC57/CIM100#'
    @property
    def __package__(self):
        return 'Common'
    @property
    def __minOccurs__(self):
        return '0'
    @property
    def __maxOccurs__(self):
        return 'unbounded'
    
@stereotype(CIMStereotype.Compound)
@dataclass(repr=False)
class Status(Identity):
    '''
    Current status information relevant to an entity.
    '''

    dateTime: Optional[str] = field(
        default=None,
        metadata={
        'type': 'Attribute',
        'stereotypes': ['Attribute'],
        'minOccurs': '0',
        'maxOccurs': '1',
        'namespace': 'http://iec.ch/TC57/CIM100#',
        'serialize': True,
        })
    '''
    Date and time for which status 'value' applies.
    '''
    
    reason: Optional[str] = field(
        default=None,
        metadata={
        'type': 'Attribute',
        'stereotypes': ['Attribute'],
        'minOccurs': '0',
        'maxOccurs': '1',
        'namespace': 'http://iec.ch/TC57/CIM100#',
        'serialize': True,
        })
    '''
    Reason code or explanation for why an object went to the current status
    'value'.
    '''
    
    remark: Optional[str] = field(
        default=None,
        metadata={
        'type': 'Attribute',
        'stereotypes': ['Attribute'],
        'minOccurs': '0',
        'maxOccurs': '1',
        'namespace': 'http://iec.ch/TC57/CIM100#',
        'serialize': True,
        })
    '''
    Pertinent information regarding the current 'value', as free form text.
    '''
    
    value: Optional[str] = field(
        default=None,
        metadata={
        'type': 'Attribute',
        'stereotypes': ['Attribute'],
        'minOccurs': '0',
        'maxOccurs': '1',
        'namespace': 'http://iec.ch/TC57/CIM100#',
        'serialize': True,
        })
    '''
    Status value at 'dateTime'; prior status changes may have been kept
    in instances of activity records associated with the object to which
    this status applies.
    '''
    
    @property
    def __namespace__(self):
        return 'http://iec.ch/TC57/CIM100#'
    @property
    def __package__(self):
        return 'Common'
    @property
    def __minOccurs__(self):
        return '0'
    @property
    def __maxOccurs__(self):
        return 'unbounded'
    
@stereotype(CIMStereotype.Compound)
@dataclass(repr=False)
class StreetAddress(Identity):
    '''
    General purpose street and postal address information.
    '''

    language: Optional[str] = field(
        default=None,
        metadata={
        'type': 'Attribute',
        'stereotypes': ['Attribute'],
        'minOccurs': '0',
        'maxOccurs': '1',
        'namespace': 'http://iec.ch/TC57/CIM100#',
        'serialize': True,
        })
    '''
    The language in which the address is specified, using ISO 639-1 two
    digit language code.
    '''
    
    poBox: Optional[str] = field(
        default=None,
        metadata={
        'type': 'Attribute',
        'stereotypes': ['Attribute'],
        'minOccurs': '0',
        'maxOccurs': '1',
        'namespace': 'http://iec.ch/TC57/CIM100#',
        'serialize': True,
        })
    '''
    Post office box.
    '''
    
    postalCode: Optional[str] = field(
        default=None,
        metadata={
        'type': 'Attribute',
        'stereotypes': ['Attribute'],
        'minOccurs': '0',
        'maxOccurs': '1',
        'namespace': 'http://iec.ch/TC57/CIM100#',
        'serialize': True,
        })
    '''
    Postal code for the address.
    '''
    
    @property
    def __namespace__(self):
        return 'http://iec.ch/TC57/CIM100#'
    @property
    def __package__(self):
        return 'Common'
    @property
    def __minOccurs__(self):
        return '0'
    @property
    def __maxOccurs__(self):
        return 'unbounded'
    
@stereotype(CIMStereotype.Compound)
@dataclass(repr=False)
class StreetDetail(Identity):
    '''
    Street details, in the context of address.
    '''

    addressGeneral: Optional[str] = field(
        default=None,
        metadata={
        'type': 'Attribute',
        'stereotypes': ['Attribute'],
        'minOccurs': '0',
        'maxOccurs': '1',
        'namespace': 'http://iec.ch/TC57/CIM100#',
        'serialize': True,
        })
    '''
    First line of a free form address or some additional address information
    (for example a mail stop).
    '''
    
    addressGeneral2: Optional[str] = field(
        default=None,
        metadata={
        'type': 'Attribute',
        'stereotypes': ['Attribute'],
        'minOccurs': '0',
        'maxOccurs': '1',
        'namespace': 'http://iec.ch/TC57/CIM100#',
        'serialize': True,
        })
    '''
    (if applicable) Second line of a free form address.
    '''
    
    addressGeneral3: Optional[str] = field(
        default=None,
        metadata={
        'type': 'Attribute',
        'stereotypes': ['Attribute'],
        'minOccurs': '0',
        'maxOccurs': '1',
        'namespace': 'http://iec.ch/TC57/CIM100#',
        'serialize': True,
        })
    '''
    (if applicable) Third line of a free form address.
    '''
    
    buildingName: Optional[str] = field(
        default=None,
        metadata={
        'type': 'Attribute',
        'stereotypes': ['Attribute'],
        'minOccurs': '0',
        'maxOccurs': '1',
        'namespace': 'http://iec.ch/TC57/CIM100#',
        'serialize': True,
        })
    '''
    (if applicable) In certain cases the physical location of the place
    of interest does not have a direct point of entry from the street,
    but may be located inside a larger structure such as a building, complex,
    office block, apartment, etc.
    '''
    
    code: Optional[str] = field(
        default=None,
        metadata={
        'type': 'Attribute',
        'stereotypes': ['Attribute'],
        'minOccurs': '0',
        'maxOccurs': '1',
        'namespace': 'http://iec.ch/TC57/CIM100#',
        'serialize': True,
        })
    '''
    (if applicable) Utilities often make use of external reference systems,
    such as those of the town-planner's department or surveyor general's
    mapping system, that allocate global reference codes to streets.
    '''
    
    floorIdentification: Optional[str] = field(
        default=None,
        metadata={
        'type': 'Attribute',
        'stereotypes': ['Attribute'],
        'minOccurs': '0',
        'maxOccurs': '1',
        'namespace': 'http://iec.ch/TC57/CIM100#',
        'serialize': True,
        })
    '''
    The identification by name or number, expressed as text, of the floor
    in the building as part of this address.
    '''
    
    name: Optional[str] = field(
        default=None,
        metadata={
        'type': 'Attribute',
        'stereotypes': ['Attribute'],
        'minOccurs': '0',
        'maxOccurs': '1',
        'namespace': 'http://iec.ch/TC57/CIM100#',
        'serialize': True,
        })
    '''
    Name of the street.
    '''
    
    number: Optional[str] = field(
        default=None,
        metadata={
        'type': 'Attribute',
        'stereotypes': ['Attribute'],
        'minOccurs': '0',
        'maxOccurs': '1',
        'namespace': 'http://iec.ch/TC57/CIM100#',
        'serialize': True,
        })
    '''
    Designator of the specific location on the street.
    '''
    
    prefix: Optional[str] = field(
        default=None,
        metadata={
        'type': 'Attribute',
        'stereotypes': ['Attribute'],
        'minOccurs': '0',
        'maxOccurs': '1',
        'namespace': 'http://iec.ch/TC57/CIM100#',
        'serialize': True,
        })
    '''
    Prefix to the street name. For example: North, South, East, West.
    '''
    
    suffix: Optional[str] = field(
        default=None,
        metadata={
        'type': 'Attribute',
        'stereotypes': ['Attribute'],
        'minOccurs': '0',
        'maxOccurs': '1',
        'namespace': 'http://iec.ch/TC57/CIM100#',
        'serialize': True,
        })
    '''
    Suffix to the street name. For example: North, South, East, West.
    '''
    
    suiteNumber: Optional[str] = field(
        default=None,
        metadata={
        'type': 'Attribute',
        'stereotypes': ['Attribute'],
        'minOccurs': '0',
        'maxOccurs': '1',
        'namespace': 'http://iec.ch/TC57/CIM100#',
        'serialize': True,
        })
    '''
    Number of the apartment or suite.
    '''
    
    type: Optional[str] = field(
        default=None,
        metadata={
        'type': 'Attribute',
        'stereotypes': ['Attribute'],
        'minOccurs': '0',
        'maxOccurs': '1',
        'namespace': 'http://iec.ch/TC57/CIM100#',
        'serialize': True,
        })
    '''
    Type of street. Examples include: street, circle, boulevard, avenue,
    road, drive, etc.
    '''
    
    withinTownLimits: Optional[bool] = field(
        default=None,
        metadata={
        'type': 'Attribute',
        'stereotypes': ['Attribute'],
        'minOccurs': '0',
        'maxOccurs': '1',
        'namespace': 'http://iec.ch/TC57/CIM100#',
        'serialize': True,
        })
    '''
    True if this street is within the legal geographical boundaries of
    the specified town (default).
    '''
    
    @property
    def __namespace__(self):
        return 'http://iec.ch/TC57/CIM100#'
    @property
    def __package__(self):
        return 'Common'
    @property
    def __minOccurs__(self):
        return '0'
    @property
    def __maxOccurs__(self):
        return 'unbounded'
    
@stereotype(CIMStereotype.Compound)
@dataclass(repr=False)
class TownDetail(Identity):
    '''
    Town details, in the context of address.
    '''

    code: Optional[str] = field(
        default=None,
        metadata={
        'type': 'Attribute',
        'stereotypes': ['Attribute'],
        'minOccurs': '0',
        'maxOccurs': '1',
        'namespace': 'http://iec.ch/TC57/CIM100#',
        'serialize': True,
        })
    '''
    Town code.
    '''
    
    country: Optional[str] = field(
        default=None,
        metadata={
        'type': 'Attribute',
        'stereotypes': ['Attribute'],
        'minOccurs': '0',
        'maxOccurs': '1',
        'namespace': 'http://iec.ch/TC57/CIM100#',
        'serialize': True,
        })
    '''
    Name of the country.
    '''
    
    name: Optional[str] = field(
        default=None,
        metadata={
        'type': 'Attribute',
        'stereotypes': ['Attribute'],
        'minOccurs': '0',
        'maxOccurs': '1',
        'namespace': 'http://iec.ch/TC57/CIM100#',
        'serialize': True,
        })
    '''
    Town name.
    '''
    
    section: Optional[str] = field(
        default=None,
        metadata={
        'type': 'Attribute',
        'stereotypes': ['Attribute'],
        'minOccurs': '0',
        'maxOccurs': '1',
        'namespace': 'http://iec.ch/TC57/CIM100#',
        'serialize': True,
        })
    '''
    Town section. For example, it is common for there to be 36 sections
    per township.
    '''
    
    stateOrProvince: Optional[str] = field(
        default=None,
        metadata={
        'type': 'Attribute',
        'stereotypes': ['Attribute'],
        'minOccurs': '0',
        'maxOccurs': '1',
        'namespace': 'http://iec.ch/TC57/CIM100#',
        'serialize': True,
        })
    '''
    Name of the state or province.
    '''
    
    @property
    def __namespace__(self):
        return 'http://iec.ch/TC57/CIM100#'
    @property
    def __package__(self):
        return 'Common'
    @property
    def __minOccurs__(self):
        return '0'
    @property
    def __maxOccurs__(self):
        return 'unbounded'
    
