"""Build pre-baked merged profile __init__.py files from merge_releases.yaml.

Run from the repo root:
    python scripts/build_merged_profiles.py

Each entry in merge_releases.yaml produces a committed __init__.py that
re-exports the merged class surface. The file is a normal Python module —
Pylance reads it directly, and `import cimgraph.data_profile.<name> as cim`
resolves to the merged class set with no runtime merge machinery needed.

Add this to the PyPI release process for any profile listed in the config.
"""
from __future__ import annotations

import importlib
import sys
import textwrap
from pathlib import Path

import yaml

_REPO_ROOT = Path(__file__).parent.parent
_CONFIG = _REPO_ROOT / "cimgraph" / "data_profile" / "merge_releases.yaml"

# Ensure the repo is importable when run directly.
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))


def _load_config() -> list[dict]:
    with open(_CONFIG) as f:
        data = yaml.safe_load(f)
    return data["releases"]


def _build_init(release: dict) -> str:
    """Return the generated __init__.py content for one release entry."""
    from cimgraph.data_profile.merge import merge_profiles

    parts = release["parts"]
    description = release.get("description", "")
    package = release["package"]

    modules = [importlib.import_module(p) for p in parts]
    merged = merge_profiles(*modules)

    names = sorted(merged.__all__)

    # Build the import block — group all names into one import from the
    # first sub-module that defines each name, keyed by sub-module path.
    # For the committed file we import from each sub-profile directly so
    # the source of each class is traceable.
    name_to_part: dict[str, str] = {}
    for part_path, mod in zip(parts, modules):
        for name in getattr(mod, "__all__", []):
            if name not in name_to_part:
                name_to_part[name] = part_path

    # Group by source part, preserving parts order.
    from collections import defaultdict
    part_to_names: dict[str, list[str]] = defaultdict(list)
    for name in names:
        src = name_to_part.get(name, parts[0])
        part_to_names[src].append(name)

    import_lines: list[str] = []
    for part_path in parts:
        part_names = part_to_names.get(part_path, [])
        if not part_names:
            continue
        header = f"from {part_path} import ("
        joined = ", ".join(part_names)
        # Wrap only the names portion so long module paths don't cause
        # textwrap to break class names mid-word.
        wrapped_names = textwrap.fill(
            joined,
            width=88,
            initial_indent="    ",
            subsequent_indent="    ",
            break_long_words=False,
            break_on_hyphens=False,
        )
        import_lines.append(f"{header}\n{wrapped_names})")

    all_entries = "\n".join(f"    '{n}'," for n in names)

    parts_comment = "\n".join(f"#   {p}" for p in parts)

    return f'''\
"""Merged profile: {package}

{description}

Parts:
{parts_comment}

Generated by scripts/build_merged_profiles.py — do not edit by hand.
Re-run the script after adding or updating sub-profile parts.
"""
from __future__ import annotations

{chr(10).join(import_lines)}

__all__ = [
{all_entries}
]
'''


def main() -> None:
    releases = _load_config()
    for release in releases:
        name = release["name"]
        package = release["package"]

        print(f"Building {package} ...")
        content = _build_init(release)

        # Write to the package __init__.py.
        package_dir = _REPO_ROOT / Path(*package.split("."))
        if not package_dir.is_dir():
            raise FileNotFoundError(
                f"Package directory not found: {package_dir}\n"
                f"Create it and add sub-profile packages before running this script."
            )

        init_path = package_dir / "__init__.py"
        init_path.write_text(content, encoding="utf-8")
        print(f"  wrote {init_path.relative_to(_REPO_ROOT)}")

        # Smoke-test: the written file must be importable and expose __all__.
        if package in sys.modules:
            del sys.modules[package]
        mod = importlib.import_module(package)
        assert hasattr(mod, "__all__"), f"{package}.__all__ missing after write"
        print(f"  ok — {len(mod.__all__)} classes exported")


if __name__ == "__main__":
    main()
