from __future__ import annotations
import logging
from dataclasses import dataclass, field
from typing import Optional
from enum import Enum
from cimgraph.data_profile.identity import Identity, stereotype
from cimgraph.data_profile.units import CIMUnit, UnitSymbol, UnitMultiplier
_log = logging.getLogger(__name__)
'''
Annotated CIMantic Graphs data profile for MarketDER
Generated by CIMTool http://cimtool.org
'''

class CIMStereotype(Enum):
    Attribute = "Attribute"
    Concrete = "Concrete"
    Primitive = "Primitive"
    enumeration = "enumeration"

BASE_URI = 'https://ucaiug.org/2023/MarketDER#'
ONTOLOGY_URI = 'http://cim.ucaiug.io/CIM101/draft#'

@dataclass(repr=False)
class IdentifiedObject(Identity):
    '''
    This is a class that provides common identification for all classes needing
    identification and naming attributes.
    '''

    __namespace__ = 'http://cim.ucaiug.io/CIM101/draft#'
    __package__ = 'Core'
    __minOccurs__ = '0'
    __maxOccurs__ = 'unbounded'
    
    mRID: Optional[str] = field(
        default=None,
        metadata={
        'type': 'Attribute',
        'minOccurs': '1',
        'maxOccurs': '1',
        'namespace': 'http://cim.ucaiug.io/CIM101/draft#',
        'docstring':
            '''
            Master resource identifier issued by a model authority. The mRID is unique
            within an exchange context. Global uniqueness is easily achieved by using
            a UUID, as specified in IETF RFC 4122, for the mRID. The use of UUID is
            strongly recommended.
            For CIMXML data files in RDF syntax conforming to IEC 61970-552, the mRID
            is mapped to rdf:ID or rdf:about attributes that identify CIM object elements.
            '''
        
        })
    '''
    Master resource identifier issued by a model authority. The mRID is
    unique within an exchange context. Global uniqueness is easily achieved
    by using a UUID, as specified in IETF RFC 4122, for the mRID. The use
    of UUID is strongly recommended.
    For CIMXML data files in RDF syntax conforming to IEC 61970-552, the
    mRID is mapped to rdf:ID or rdf:about attributes that identify CIM
    object elements.
    '''
    
    name: Optional[str] = field(
        default=None,
        metadata={
        'type': 'Attribute',
        'minOccurs': '0',
        'maxOccurs': '1',
        'namespace': 'http://cim.ucaiug.io/CIM101/draft#',
        'docstring':
            '''
            The name is any free human readable and possibly non unique text naming
            the object.
            '''
        
        })
    '''
    The name is any free human readable and possibly non unique text naming
    the object.
    '''
    
@dataclass(repr=False)
class IndividualPnode(IdentifiedObject):
    '''
    Individual pricing node based on Pnode.
    '''

    __namespace__ = 'http://cim.ucaiug.io/CIM101/draft#'
    __package__ = 'ReferenceData'
    __minOccurs__ = '0'
    __maxOccurs__ = 'unbounded'
    
@dataclass(repr=False)
class RegisteredResource(IdentifiedObject):
    '''
    A resource that is registered through the market participant registration
    system. Examples include generating unit, load, and non-physical generator
    or load.
    '''

    __namespace__ = 'http://cim.ucaiug.io/CIM101/draft#'
    __package__ = 'MarketCommon'
    __minOccurs__ = '0'
    __maxOccurs__ = 'unbounded'
    
    isAggregatedRes: Optional[ YesNo ] = field(
        default=None,
        metadata={
        'type': 'enumeration',
        'minOccurs': '1',
        'maxOccurs': '1',
        'namespace': 'http://cim.ucaiug.io/CIM101/draft#',
        'docstring':
            '''
            A flag to indicate if a resource is an aggregated resource.
            '''
        
        })
    '''
    A flag to indicate if a resource is an aggregated resource.
    '''
    
    registrationStatus: Optional[ ResourceRegistrationStatus ] = field(
        default=None,
        metadata={
        'type': 'enumeration',
        'minOccurs': '1',
        'maxOccurs': '1',
        'namespace': 'http://cim.ucaiug.io/CIM101/draft#',
        'docstring':
            '''
            Current state of the resource registration which describes the lifecycle
            from initial design through to eventual decommissioning.
            '''
        
        })
    '''
    Current state of the resource registration which describes the lifecycle
    from initial design through to eventual decommissioning.
    '''
    
    Pnode: Optional[IndividualPnode] = field(
        default=None,
        metadata={
        'type': 'Attribute',
        'minOccurs': '1',
        'maxOccurs': '1',
        'inverse': 'Pnode.RegisteredResources',
        'namespace': 'http://cim.ucaiug.io/CIM101/draft#',
        'docstring':
            '''
            A registered resource injects power at one or more connectivity nodes related
            to a pnode
            '''
        
        })
    '''
    A registered resource injects power at one or more connectivity nodes
    related to a pnode
    '''
    
    ResourceCapacity: list[ResourceCapacity] = field(
        default_factory=list,
        metadata={
        'type': 'Attribute',
        'minOccurs': '1',
        'maxOccurs': 'unbounded',
        'inverse': 'ResourceCapacity.RegisteredResource',
        'namespace': 'http://cim.ucaiug.io/CIM101/draft#',
        'docstring':
            '''
            '''
        
        })
    '''
    '''
    
@stereotype(CIMStereotype.Concrete)
@dataclass(repr=False)
class RegisteredDistributedResource(RegisteredResource):
    '''
    A registered resource that represents a distributed energy resource, such
    as a micro-generator, fuel cell, photo-voltaic energy source, etc.
    '''

    __namespace__ = 'http://cim.ucaiug.io/CIM101/draft#'
    __package__ = 'ReferenceData'
    __minOccurs__ = '1'
    __maxOccurs__ = 'unbounded'
    
    distributedResourceType: Optional[str] = field(
        default=None,
        metadata={
        'type': 'Attribute',
        'minOccurs': '1',
        'maxOccurs': '1',
        'namespace': 'http://cim.ucaiug.io/CIM101/draft#',
        'docstring':
            '''
            The type of resource. Examples include: fuel cell, flywheel, photovoltaic,
            micro-turbine, CHP (combined heat power), V2G (vehicle to grid), DES (distributed
            energy storage), and others.
            '''
        
        })
    '''
    The type of resource. Examples include: fuel cell, flywheel, photovoltaic,
    micro-turbine, CHP (combined heat power), V2G (vehicle to grid), DES
    (distributed energy storage), and others.
    '''
    
@dataclass(repr=False)
class ResourceCapacity(Identity):
    '''
    This class model the various capacities of a resource. A resource may have
    numbers of capacities related to operating, ancillary services, energy
    trade and so forth. Capacities may be defined for active power or reactive
    power.
    '''

    __namespace__ = 'http://cim.ucaiug.io/CIM101/draft#'
    __package__ = 'MarketCommon'
    __minOccurs__ = '0'
    __maxOccurs__ = 'unbounded'
    
    RegisteredResource: list[RegisteredResource] = field(
        default_factory=list,
        metadata={
        'type': 'Association',
        'minOccurs': '0',
        'maxOccurs': 'unbounded',
        'inverse': 'RegisteredResource.ResourceCapacity',
        'namespace': 'http://cim.ucaiug.io/CIM101/draft#',
        'docstring':
            '''
            '''
        
        })
    '''
    '''
    
    maximumCapacity: Optional[str] = field(
        default=None,
        metadata={
        'type': 'Attribute',
        'minOccurs': '1',
        'maxOccurs': '1',
        'namespace': 'http://cim.ucaiug.io/CIM101/draft#',
        'docstring':
            '''
            maximum capacity
            '''
        
        })
    '''
    maximum capacity
    '''
    
    minimumCapacity: Optional[str] = field(
        default=None,
        metadata={
        'type': 'Attribute',
        'minOccurs': '1',
        'maxOccurs': '1',
        'namespace': 'http://cim.ucaiug.io/CIM101/draft#',
        'docstring':
            '''
            minimum capacity
            '''
        
        })
    '''
    minimum capacity
    '''
    
    unitMultiplier: Optional[ UnitMultiplier ] = field(
        default=None,
        metadata={
        'type': 'enumeration',
        'minOccurs': '1',
        'maxOccurs': '1',
        'namespace': 'http://cim.ucaiug.io/CIM101/draft#',
        'docstring':
            '''
            Unit Multiplier selection for the capacity values.
            '''
        
        })
    '''
    Unit Multiplier selection for the capacity values.
    '''
    
    unitSymbol: Optional[ UnitSymbol ] = field(
        default=None,
        metadata={
        'type': 'enumeration',
        'minOccurs': '1',
        'maxOccurs': '1',
        'namespace': 'http://cim.ucaiug.io/CIM101/draft#',
        'docstring':
            '''
            Unit selection for the capacity values.
            '''
        
        })
    '''
    Unit selection for the capacity values.
    '''
    
@stereotype(CIMStereotype.enumeration)
class ResourceRegistrationStatus(Enum):
    '''
    Types of resource registration status.
    '''

    Active = 'Active'
    '''
    Resource registration is active
    '''
    
    Decommissioned = 'Decommissioned'
    '''
    Resource registration status is decommissioned
    '''
    
    Inactive = 'Inactive'
    '''
    Resource registration status is inactive.
    '''
    
    Mothballed = 'Mothballed'
    '''
    Resource registration has been suspended
    '''
    
    Planned = 'Planned'
    '''
    Registration status is in the planning stage
    '''
    
@stereotype(CIMStereotype.enumeration)
class UnitMultiplier(Enum):
    '''
    The unit multipliers defined for the CIM. When applied to unit symbols,
    the unit symbol is treated as a derived unit. Regardless of the contents
    of the unit symbol text, the unit symbol shall be treated as if it were
    a single-character unit symbol. Unit symbols should not contain multipliers,
    and it should be left to the multiplier to define the multiple for an entire
    data type.
    For example, if a unit symbol is "m2Pers" and the multiplier is "k", then
    the value is k(m**2/s), and the multiplier applies to the entire final
    value, not to any individual part of the value. This can be conceptualized
    by substituting a derived unit symbol for the unit type. If one imagines
    that the symbol "&#222;" represents the derived unit "m2Pers", then applying
    the multiplier "k" can be conceptualized simply as "k&#222;".
    For example, the SI unit for mass is "kg" and not "g". If the unit symbol
    is defined as "kg", then the multiplier is applied to "kg" as a whole and
    does not replace the "k" in front of the "g". In this case, the multiplier
    of "m" would be used with the unit symbol of "kg" to represent one gram.
    As a text string, this violates the instructions in IEC 80000-1. However,
    because the unit symbol in CIM is treated as a derived unit instead of
    as an SI unit, it makes more sense to conceptualize the "kg" as if it were
    replaced by one of the proposed replacements for the SI mass symbol. If
    one imagines that the "kg" were replaced by a symbol "&#222;", then it
    is easier to conceptualize the multiplier "m" as creating the proper unit
    "m&#222;", and not the forbidden unit "mkg".
    '''

    k = 'k'
    '''
    Kilo 10**3.
    '''
    
@stereotype(CIMStereotype.enumeration)
class UnitSymbol(Enum):
    '''
    The derived units defined for usage in the CIM. In some cases, the derived
    unit is equal to an SI unit. Whenever possible, the standard derived symbol
    is used instead of the formula for the derived unit. For example, the unit
    symbol Farad is defined as "F" instead of "CPerV". In cases where a standard
    symbol does not exist for a derived unit, the formula for the unit is used
    as the unit symbol. For example, density does not have a standard symbol
    and so it is represented as "kgPerm^3". With the exception of the "kg",
    which is an SI unit, the unit symbols do not contain multipliers and therefore
    represent the base derived unit to which a multiplier can be applied as
    a whole.
    Every unit symbol is treated as an unparseable text as if it were a single-letter
    symbol. The meaning of each unit symbol is defined by the accompanying
    descriptive text and not by the text contents of the unit symbol.
    To allow the widest possible range of serializations without requiring
    special character handling, several substitutions are made which deviate
    from the format described in IEC 80000-1. The division symbol "/" is replaced
    by the letters "Per". Exponents are written in plain text after the unit
    as "m^3". The letters "deg" are used instead of the degree symbol. Any
    clarification of the meaning for a substitution is included in the description
    for the unit symbol.
    Non-SI units are included in list of unit symbols to allow sources of data
    to be correctly labelled with their non-SI units (for example, a GPS sensor
    that is reporting numbers that represent feet instead of meters). This
    allows software to use the unit symbol information correctly convert and
    scale the raw data of those sources into SI-based units.
    The integer values are used for harmonization with IEC 61850.
    '''

    W = 'W'
    '''
    Real power in watts (J/s). Electrical power may have real and reactive
    components. The real portion of electrical power (I^2*R or V*I*cos(phi)),
    is expressed in Watts. See also apparent power and reactive power.
    '''
    
@stereotype(CIMStereotype.enumeration)
class YesNo(Enum):
    '''
    Used as a flag set to Yes or No.
    '''

    NO = 'NO'
    '''
    '''
    
    YES = 'YES'
    '''
    '''
    
